name: Robot Framework CI

on:
  push:
    branches: [ "qhuy" ]
  pull_request:
  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t robot-test .

      - name: Run Robot Framework tests
        run: |
          docker run --name robot-container robot-test
          docker cp robot-container:/app/results ./results
          docker rm robot-container

      - name: Upload Robot Framework results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results
