name: Robot Framework CI

on:
  push:
    branches: [ "qhuy" ]
  pull_request:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t robot-tests .

      - name: Run Robot Framework tests
        run: docker run robot-tests
